// ══════════════════════════════════════════════════════
//  WIZARD CORE — generic engine, zero platform knowledge
//  Depends on a global PLATFORM object supplied by a
//  platform-*.js file loaded BEFORE this script.
// ══════════════════════════════════════════════════════

// ══════════════════════════════════════════════════════
//  EMBEDDED CLAUDE.MD CONTENT
//  This content is written to agent-artifacts/CLAUDE.md
//  when wizard setup completes. Allows standalone agent-sdd/
//  setup where wizard can't access external folders.
// ══════════════════════════════════════════════════════
const EMBEDDED_CLAUDE_MD = `# CLAUDE.md — Agent Entry Point
# ─────────────────────────────────────────────────────────────────────────────
# READ THIS FILE COMPLETELY BEFORE DOING ANYTHING ELSE.
# This file governs every session. No exceptions.
# ─────────────────────────────────────────────────────────────────────────────
#
# 📋 HOW THIS FILE IS USED:
#
# 1. Original location: agent-sdd/CLAUDE.md (source of truth)
# 2. Copied location: agent-artifacts/CLAUDE.md (read-only snapshot)
#    → Setup wizard copies this file to agent-artifacts/ when setup completes
#    → Projects use: claude "Read agent-artifacts/CLAUDE.md and execute ..."
#    → This keeps projects self-contained (no path dependency on agent-sdd/)
# 3. Protection: agent-artifacts/CLAUDE.md is read-only (hooks block edits)
#    → To update, re-run setup wizard to get the latest version
# ─────────────────────────────────────────────────────────────────────────────

## What This Is

You are an AI agent executing a development task on a software project.
This SDD skeleton gives you everything you need to work accurately and safely:
- Project configuration (\`agent-artifacts/project.config.md\`)
- Architecture knowledge (\`agent-artifacts/spec-kit/\`)
- Per-module living docs (\`agent-artifacts/context/\`)
- The task to execute (\`agent-artifacts/tasks/<TICKET-ID>.md\`)

**Directory layout:**
- \`agent-sdd/\` — the skeleton tool (wizard, templates, **this CLAUDE.md file**). Read-only — never modify anything here.
- \`agent-artifacts/\` — your project's generated spec-kit, context files, and tasks. All agent reads and writes go here. **Does NOT contain CLAUDE.md.**

Your job: read the task MD, load the right context, write the code, update
the context files, and produce a completion report. Nothing more.

---

## Step 0 — Read project.config.md

Read \`agent-artifacts/project.config.md\` first. Extract:
- \`codebase_path\` — all source file paths resolve from here
- \`platform\` and \`primary_language\` — governs which conventions apply
- \`default_tests\` — Y means write tests unless task says otherwise
- \`branch_convention\` — for completion report

**Resolving codebase_path:** If the value starts with \`.\` (e.g. \`..\`), it is a
relative path from the \`agent-artifacts/\` folder. Resolve it to an absolute path before
using it. Example: if \`agent-artifacts/\` is at \`/project/agent-artifacts/\` and
\`codebase_path: ..\`, the resolved path is \`/project/\`.

---

## Spec-Kit File Types

Two types of files exist in \`spec-kit/\`. Both are read-only for the agent. They differ in
**how a human updates them**.

### AI Artifacts
Generated by the setup wizard from structured form input.
The file header reads \`AI-GENERATED ARTIFACT\`.
**Update workflow: re-run the wizard step → Generate & Save. Do not edit manually.**

| File | Generated by |
|------|-------------|
| \`ARCHITECTURE.md\` | Architecture wizard step |
| \`MODULE_MAP.md\` | Modules wizard step |
| \`DATA_MODEL.md\` | Data Model wizard step |

### Human-Authored Specs
Written and maintained directly by the tech lead in markdown.
The file header reads \`HUMAN-AUTHORED\`.
**Update workflow: open the file, edit, commit.**

| File | Content |
|------|---------|
| \`CONVENTIONS.md\` | Coding standards, naming conventions, quality gate |
| \`MIGRATION_RULES.md\` | Legacy → modern migration rules with scope guard |
| \`TESTING.md\` | Test patterns, naming, framework stack, coverage targets |
| \`TECH_DEBT.md\` | Known debt register with per-entry agent rules |

**Agent rule: reads all spec-kit files. Modifies none. Ever.**

---

## Step 1 — Load Tiered Context (always in this order)

Load every tier before reading the task. Do not skip tiers.

| Tier | What to load | Condition |
|------|-------------|-----------|
| 1 | \`agent-artifacts/spec-kit/ARCHITECTURE.md\` + \`agent-artifacts/spec-kit/MODULE_MAP.md\` | Always |
| 2 | \`agent-artifacts/spec-kit/CONVENTIONS.md\` + \`agent-artifacts/spec-kit/MIGRATION_RULES.md\` + \`agent-artifacts/spec-kit/TESTING.md\` | Always |
| 3 | \`agent-artifacts/context/_index.md\` → match task keywords → load \`agent-artifacts/context/<module>.md\` for each match | Always |
| 4 | Relevant sections of \`agent-artifacts/spec-kit/TECH_DEBT.md\` | When touching legacy code or files listed in debt register |
| 5 | Relevant sections of \`agent-artifacts/spec-kit/DATA_MODEL.md\` | When task touches data models, APIs, DB, or network |
| 6 | Source files listed in the loaded context files that are expected to change | Per task |

**Multi-module tasks:** If the task touches more than one module, load all matching
context files (Tier 3) before reading any source files.

**Module not in context/:** Check \`agent-artifacts/spec-kit/MODULE_MAP.md\` by module name. If still
not found, read 5–8 key source files in that area, execute the task, then generate
a \`agent-artifacts/context/<module>.md\` file afterward using \`agent-sdd/context/TEMPLATE.md\`.

---

## Step 2 — Read the Task MD

Read the task file the developer has provided (e.g., \`agent-artifacts/tasks/[PROJ]-1234.md\`).
Extract:
- Ticket ID and title
- Type (Feature / Bug / Refactor / Task)
- Description
- Acceptance criteria (these are your definition of done)
- Out of scope (treat these as hard constraints — do not implement them)
- Affected areas (use to confirm or expand Tier 3 context loading)
- Testing requirements
- Any designs or reference links

---

## Step 3 — State Your Understanding BEFORE Touching Code

Write out the following before writing a single line of code.
If anything is ambiguous, stop here (see Ambiguity Protocol below).

\`\`\`
### Understanding

**Affected modules:** [list each module]

**Context files loaded:** [list each agent-artifacts/context/<module>.md]

**Files to create:**
- path/to/NewFile.kt — [one-line reason]

**Files to modify:**
- path/to/ExistingFile.kt — [one-line reason]

**Migration rules that apply:**
- [RULE-ID]: [how it affects this task]

**Tech debt in scope:**
- [DEBT-ID]: [what it means for this task — e.g., "do not add LiveData here"]

**Ambiguities:** None / [list if any]
\`\`\`

### Ambiguity Protocol

If any acceptance criterion is unclear or contradictory:
1. Quote the exact text that is unclear
2. Ask ONE specific question
3. STOP — do not write code until the developer responds

Do not assume. Do not interpret charitably and proceed. Stop and ask.

---

## Step 4 — Confirm Tests

If the task MD specifies \`Required: Y\` or \`Required: N\` → use that.
If the task MD is silent AND \`default_tests: Y\` in \`project.config.md\` → write tests, no need to ask.
If the task MD is silent AND \`default_tests: N\` → ask: "Do you want tests for this task? [Y/N]"

---

## Step 5 — Execute

Write code following \`agent-artifacts/spec-kit/CONVENTIONS.md\` and \`agent-artifacts/spec-kit/MIGRATION_RULES.md\` exactly.
Apply \`agent-artifacts/spec-kit/TESTING.md\` for all test files.

**Execution order:**
1. Create new files first (models, repositories, use cases)
2. Modify existing files
3. Write test files last (or interleaved per TDD if specified)

---

## Step 6 — Self-Verification (do not skip)

Before writing the completion report, verify your own work.
This step is not optional. If verification fails, self-correct first, then re-verify.

### 6a — Acceptance Criteria Check

For each acceptance criterion in the task MD, state exactly how it is satisfied:

\`\`\`
- [x] Criterion 1 — verified: [specific evidence — file, function, line, test name]
- [x] Criterion 2 — verified: [specific evidence]
- [ ] Criterion 3 — BLOCKED: [exact reason — missing API / external dependency / out of scope]
\`\`\`

"I implemented it" is not evidence. Name the file, function, or test that proves it.

If a criterion is **blocked**, stop here. Surface it to the developer before proceeding.
Do not mark it done. Do not work around it silently.

### 6b — Quality Gate

Scan every file you created or modified against these checks:

| Check | Rule |
|-------|------|
| No \`!!\` operators | Use \`?.let {}\`, \`?: return\`, or \`requireNotNull\` |
| No new \`LiveData\` | New state uses \`StateFlow\` only |
| No \`GlobalScope\` | All coroutines in \`viewModelScope\` or \`lifecycleScope\` |
| No hardcoded strings | All user-visible text in \`strings.xml\` |
| No hardcoded colors or dimensions | Use theme attributes or \`dimens.xml\` |
| Sealed types are exhaustive | No \`else\` on \`when\` over sealed class/interface |
| No business logic in UI layer | Composables, Fragments, Activities call ViewModel only |
| ViewModel has no Android imports | No \`Context\`, \`View\`, \`FragmentManager\` |
| DTOs/Entities not exposed to UI | Repository returns domain models only |
| Tests follow TESTING.md naming | \`functionName_scenario_expectedResult\` |

For each failure found: **fix it before proceeding.** Log what you fixed under Self-Corrections.

### 6c — Self-Corrections

List every fix you made during verification:

\`\`\`
- [File:line] — [what was wrong] → [what was changed]
\`\`\`

If none: write "None."

### 6d — Verdict

\`\`\`
Verdict: PASS / BLOCKED

If BLOCKED: [state exactly what is missing and what the developer needs to provide]
\`\`\`

Only proceed to Step 7 if verdict is **PASS**.

---

## Step 7 — Update Context Files

After verification passes, update \`agent-artifacts/context/<module>.md\` for every module you touched:
- Add new files to the Key Files table
- Update State Management if ViewModel state changed
- Update Known Debt if new debt was introduced
- Update Tests section with new test files
- Update "What the Agent Should Know" with any non-obvious discoveries
- Set "Last updated" to today's date and the ticket ID

If a module had no context file, create one using \`agent-sdd/context/TEMPLATE.md\`.

---

## Step 8 — Write Completion Report

Use this exact format:

\`\`\`
## Done — [TICKET-ID]: [Title]

### Files created
- path/to/NewFile.kt

### Files modified
- path/to/ExistingFile.kt — [one line: what changed and why]

### Context files updated
- agent-artifacts/context/[module].md — [one line: what was added or changed]

### Tests written
- path/to/NewFileTest.kt — [scenarios covered]

### Acceptance criteria
- [x] Criterion 1 — verified: [specific evidence]
- [x] Criterion 2 — verified: [specific evidence]
- [ ] Criterion 3 — BLOCKED: [reason]

### Quality gate
- [x] All checks passed
- [ ] [Any check that required a self-correction — describe what was fixed]

### Self-corrections
- [File:line] — [what was wrong] → [what was changed]
- None (if no corrections were needed)

### Excluded from this ticket
- [anything intentionally omitted and why]

### Follow-up recommended
- [new debt introduced: DEBT-ID, location, description]
- [violation noticed but out of scope: file:line, what was observed]
\`\`\`

---

## Hard Rules

These rules have no exceptions. Do not reason around them.

### Scope rules
- **Never modify \`agent-sdd/\` files.** This is the skeleton submodule — wizard, templates, this CLAUDE.md. Read-only for everyone including the agent.
- **Never modify \`agent-artifacts/spec-kit/\` files.** These are read-only inputs — some are AI artifacts generated by the wizard, some are human-authored specs. The agent reads both and modifies neither.
- **Never create new top-level directories** in the codebase without explicit instruction.
- **Never fix tech debt outside task scope.** Log it in the completion report instead.
- **Never refactor code the task did not ask you to touch.** Diffs must be reviewable.

### Code quality rules (Android/Kotlin defaults — see CONVENTIONS.md for overrides)
- No \`!!\` null assertions. Use \`?.let {}\`, \`?: return\`, or \`requireNotNull(x) { "message" }\`.
- No hardcoded strings, colors, or dimensions. Use resource files.
- No business logic in the UI layer (Composables, XML layouts, Fragments, Views, Activities).
- Every \`when\` on a sealed class or sealed interface must be exhaustive. No \`else\` on sealed types.
- No \`GlobalScope\`. All coroutines in \`viewModelScope\` (or \`lifecycleScope\` for one-shot UI ops).
- Never introduce new \`LiveData\`. New state uses \`StateFlow\` only.
- Never convert Java to Kotlin unless the task explicitly instructs it.
- No \`lateinit var\` except for Hilt-injected fields.

### For non-Android platforms
The rules above are Android/Kotlin defaults. \`agent-artifacts/spec-kit/CONVENTIONS.md\` defines the
equivalent rules for your platform. CONVENTIONS.md takes precedence over this list.

---

## Runtime Protection (Claude Code Hooks)

The project's \`.claude/settings.json\` (installed from \`agent-sdd/hooks/\`) enforces protection rules that run **before** this file is even read:

| Layer | What it enforces |
|-------|-----------------|
| \`permissions.deny\` | Blocks all writes to \`agent-sdd/**\`, \`agent-artifacts/spec-kit/**\`, generated files (\`.xcodeproj\`, \`R.java\`, \`BuildConfig.java\`, \`*.generated.kt\`, \`build/\`) |
| \`protected-paths.sh\` (PreToolUse) | Script-level catch for edge cases the glob patterns miss |
| \`lint-gate.sh\` (PostToolUse) | Runs ktlint (Android) or SwiftLint (iOS) after every file edit |
| \`done-gate.sh\` (Stop) | Audits \`git diff\` on session end and warns about any protected-file touches |

These hooks are **deterministic** — they run regardless of what this file says. CLAUDE.md is the fallback for behavior the hooks don't cover (logic, naming, structure). Never attempt to write to protected paths; the hook will block it and the task will stall.

---

## What Good Looks Like

A well-executed task:
- Every acceptance criterion is verified with **specific evidence** (file, function, test name) — not just checked off
- Quality gate is clean — no violations slipped through to the completion report
- Self-corrections are logged transparently — the developer can see what the agent caught and fixed
- Diffs are minimal — only code the task required was touched
- Context files are updated so the next agent session starts smarter
- Completion report is honest — blocked criteria and new debt are surfaced, not hidden
- Code follows CONVENTIONS.md exactly — naming, structure, patterns
`;

// ── Embedded: tasks/TASK_TEMPLATE.md ──────────────────
const EMBEDDED_TASK_TEMPLATE = `# Task: [TICKET-ID] — [Title]
# ─────────────────────────────────────────────────────────────────────────────
# HOW TO USE:
# 1. Rename this file: PROJ-1234.md
# 2. Fill in every section below (remove comments as you go)
# 3. From your project terminal run:
#    claude "Read agent-artifacts/CLAUDE.md and execute agent-artifacts/tasks/PROJ-1234.md"
# ─────────────────────────────────────────────────────────────────────────────

## Type

- [ ] Feature
- [ ] Bug
- [ ] Refactor
- [ ] Task

## Description

<!--
What needs to be done and why.
Include user-facing impact if relevant.
1–5 sentences. Be specific about what changes, not just what the outcome is.

Good: "Add a store_selected Firebase event fired when the user taps a store in
SelectStoreFragment. The event must include store_id as a property."
Bad: "Track store selection in analytics."
-->

[Description here]

## Acceptance Criteria

<!--
Each criterion must be verifiable — the agent should be able to point to a
specific file, function, or test result as evidence.

Good: "TrackStoreSelectedEvent is called in SelectStoreFragment.onStoreClicked()
with the correct store_id property."
Bad: "Store selection is tracked."

The agent checks each one with evidence in the completion report.
If a criterion cannot be verified, it is marked BLOCKED with a reason.
-->

- [ ] [Criterion 1 — what is true when this is done, stated precisely]
- [ ] [Criterion 2]
- [ ] [Criterion 3]

## Quality Gate

<!--
Technical checks the agent must pass before marking the task complete.
Leave defaults unless your task has specific overrides.
-->

- [ ] No \`!!\` operators introduced
- [ ] No new \`LiveData\` introduced — new state uses \`StateFlow\`
- [ ] No hardcoded strings, colors, or dimensions
- [ ] All \`when\` on sealed types are exhaustive — no \`else\`
- [ ] No business logic in UI layer
- [ ] Tests follow \`functionName_scenario_expectedResult\` naming
- [ ] [Add task-specific check if needed]

## Out of Scope

<!--
Explicitly state what NOT to do. This prevents over-engineering.
Even if related, if it's not in scope, list it here.

Example: "Do not track this event in Adjust — Firebase only."
-->

- [Out of scope item 1]

## Affected Areas

<!--
A one-line hint that helps the agent load the right context files faster.
Use module names, feature names, or file names.

Example: "analytics, store selection flow, SelectStoreFragment"
-->

[e.g., analytics, basket flow, checkout screen]

## Testing

Required: Y / N

<!--
If Y, specify the level and key scenarios.
Write scenarios as verifiable statements — the agent checks each one off.
If N, the agent will still log what could be tested in the completion report.
-->

Level: Unit / Integration / Both

Scenarios:
- [ ] [Scenario 1 — e.g., "event fires with correct store_id when store is tapped"]
- [ ] [Scenario 2 — e.g., "event does not fire when store selection is cancelled"]

## Designs / References

<!--
Figma links, Confluence pages, API docs, Jira tickets, local file paths.
If none, write "None."
-->

- [Link or file path]

## Notes

<!--
Backend changes required? API contracts changing?
Known gotchas or edge cases?
Dependency on another in-progress ticket?
Leave blank if none.
-->

[Notes here or remove section]
`;

// ── Embedded: tasks/BOOTSTRAP_TEMPLATE.md ─────────────
const EMBEDDED_BOOTSTRAP_TEMPLATE = `# Task: BOOTSTRAP — Generate context file for [Module Name]

## Type

- [ ] Bug
- [ ] Feature
- [ ] Refactor
- [x] Task

## Description

**This is a context discovery run — no code changes.**

On day 1 of adopting the Agentic SDD system, context files do not exist yet.
Without them, the agent falls back to scanning source files on every task, which
is slower and more error-prone.

Run this task once per module to generate its \`context/<module>.md\` file.
The agent reads the source files, extracts structure, and writes the context file.
No production code is created or modified.

Replace \`[Module Name]\` and the file paths below with the actual module details
from \`spec-kit/MODULE_MAP.md\` before running.

## Acceptance Criteria

- [ ] \`context/<module>.md\` exists and follows the structure in \`context/TEMPLATE.md\`
- [ ] Key Files table is populated with actual file paths (relative to \`codebase_path\`)
- [ ] State Management section describes what the ViewModel exposes (or notes "N/A" if no ViewModel)
- [ ] Dependencies section lists what this module imports and what imports it
- [ ] "What the Agent Should Know" section contains at least one non-obvious fact, or notes "None found"
- [ ] Known Debt section lists any OPEN patterns found during the scan, or notes "None found"
- [ ] Tests section lists existing test files, or notes "No tests found"
- [ ] A routing row for this module is added to \`context/_index.md\`

## Quality Gate

- [ ] No production source files were created or modified
- [ ] No \`spec-kit/\` files were modified (read-only)
- [ ] Context file uses the exact section structure from \`context/TEMPLATE.md\`
- [ ] All file paths in Key Files table are verified to exist

## Out of Scope

- Do NOT fix any code issues discovered during the scan — log them in the completion report
- Do NOT create unit tests — this is a read-only discovery run
- Do NOT modify \`spec-kit/MODULE_MAP.md\` — add routing to \`context/_index.md\` only

## Module to Bootstrap

Fill in before running:

\`\`\`
Module name:    [e.g., :app/profile]
Source path:    [e.g., app/src/main/java/com/example/views/profile/]
Key classes:    [list from MODULE_MAP.md — e.g., ProfileViewModel.kt, ProfileFragment.kt]
Context file:   [e.g., context/profile.md]
\`\`\`

## Affected Areas

[Copy keywords from MODULE_MAP.md entry for this module]

## Testing

- [ ] Not required — this is a read-only context generation task

## Steps for the Agent

1. Read \`agent-artifacts/spec-kit/MODULE_MAP.md\` — find the entry for the module being bootstrapped.
2. Read the key source files listed in the \`Key classes\` field.
3. For each file: extract purpose, public interface, state shape, and dependencies.
4. Scan for tech debt patterns listed in \`agent-artifacts/spec-kit/TECH_DEBT.md\`.
5. Scan for existing test files (\`*Test.kt\`, \`*Spec.kt\`) in the module path.
6. Populate \`agent-artifacts/context/TEMPLATE.md\` fields from what you observed.
7. Save as \`agent-artifacts/context/<module>.md\`.
8. Add a routing row to \`agent-artifacts/context/_index.md\`.
9. Write a completion report listing what was found and any debt or gaps discovered.

## Notes

Bootstrap runs are fast — typically 5–8 source file reads per module.
Do all modules in \`spec-kit/MODULE_MAP.md\` before starting feature tickets.
Modules bootstrapped first: those most commonly touched by the current backlog.
`;

// ── Embedded: context/TEMPLATE.md ─────────────────────
const EMBEDDED_CONTEXT_TEMPLATE = `# context/[module-name].md
# ─────────────────────────────────────────────────────────────────────────────
# COPY THIS FILE to create a new module context file.
# Rename to match the module: context/auth.md, context/ordering.md, etc.
# Add a row to context/_index.md pointing to this file.
#
# This file is updated by the agent after every task that touches this module.
# Review context file changes in PRs alongside the code changes.
# ─────────────────────────────────────────────────────────────────────────────

## Module: [Module Name]

**Last updated**: [YYYY-MM-DD] by [agent / human], after [TICKET-ID or "bootstrap"]
**Architecture**: [MVVM / MVP / Clean / None / Mixed]
**Language**: [Kotlin / Kotlin + Java / Swift / TypeScript]
**DI**: [Hilt / Dagger / Manual / None]

---

## Purpose

[2–3 sentences. What user-facing features live here. What this module does NOT do — boundaries matter.]

---

## Key Files

| File (relative to codebase_path) | Role |
|----------------------------------|------|
| \`path/to/[Name]ViewModel.kt\` | [one-line description] |
| \`path/to/[Name]Repository.kt\` | [one-line description] |
| \`path/to/[Name]Fragment.kt\` | [one-line description] |
| \`path/to/di/[Name]Module.kt\` | [one-line description] |

---

## State Management

[Describe how state flows through this module. What the ViewModel exposes. Sealed class shapes.]

\`\`\`kotlin
// Example — fill in actual state for this module:
sealed interface [Name]UiState {
    data object Idle : [Name]UiState
    data object Loading : [Name]UiState
    data class Error(val message: String) : [Name]UiState
    data object Success : [Name]UiState
}
\`\`\`

---

## Dependencies

- **Depends on**: [list modules this imports — e.g., \`:core-network\`, \`:core-data\`]
- **Depended on by**: [list modules that import this — e.g., \`:app\` (NavGraph)]

---

## Known Debt

- [DEBT-XXX — one-line description. See \`spec-kit/TECH_DEBT.md#[section]\` for agent rules.]

No debt — leave this section empty if none.

---

## Tests

| Test file | What it covers |
|-----------|---------------|
| \`path/to/[Name]ViewModelTest.kt\` | [scenarios covered] |
| \`path/to/[Name]RepositoryTest.kt\` | [scenarios covered] |

**Coverage gaps**: [list untested scenarios that would be valuable to add]

---

## What the Agent Should Know

[Non-obvious facts. Gotchas. Invariants. Workarounds that must not be removed. Side effects.]

- "Never call [Class] directly from ViewModel — always through [UseCase]"
- "[Field] is nullable in the API response but the UI assumes non-null — guard here"
- "The [workaround] in [File]:L42 exists because [reason] — do not simplify it"
`;

// ── Embedded: context/_index.md ───────────────────────
const EMBEDDED_CONTEXT_INDEX = `# Context Index
# ─────────────────────────────────────────────────────────────────────────────
# THIS IS THE AUTHORITATIVE ROUTING TABLE.
# Agent uses this table — and only this table — to decide which
# context/<module>.md files to load for a given task.
# spec-kit/MODULE_MAP.md is the module registry (metadata); this file routes.
# Seeded by humans; grows as new modules are added.
# ─────────────────────────────────────────────────────────────────────────────

## How to Use (Agent)

1. Read the task MD: description, acceptance criteria, affected areas.
2. Match task keywords against the Keywords column in this file.
3. Load every context file that matches before reading any source files.
4. If no match: check \`spec-kit/MODULE_MAP.md\` by package/module name for richer metadata.
5. If still no match: read 5–8 key source files, then generate a context file afterward.

For tasks touching >1 module: load ALL matching context files, then proceed.

---

## Keyword Routing Table

| Keywords | Module | Context File |
|----------|--------|--------------|
| login, logout, sign in, sign out, session, token, auth, biometric, password, register, authentication | Authentication | \`context/auth.md\` |
| home, dashboard, feed, landing, main screen, summary | Home | \`context/home.md\` |
| profile, account, settings, preferences, avatar, edit profile | Profile / Settings | \`context/profile.md\` |
| payment, checkout, billing, card, transaction, purchase, order | Payment / Checkout | \`context/checkout.md\` |
| onboarding, splash, welcome, walkthrough, first launch | Onboarding | \`context/onboarding.md\` |
| notification, push, FCM, alert, badge, messaging | Notifications | \`context/notifications.md\` |
| network, API, http, retrofit, endpoint, interceptor, base url | Core Network | \`context/core-network.md\` |
| database, room, datastore, cache, local storage, preferences, dao | Core Data | \`context/core-data.md\` |
| theme, color, typography, design token, shared component, button, card, composable | Core UI | \`context/core-ui.md\` |
| analytics, tracking, firebase, event, screen view | Analytics | \`context/analytics.md\` |

<!-- Add a row here whenever you add a new context/<module>.md file. -->

---

## Notes for Humans

- \`_index.md\` (this file) — agent routing table: keyword → context file
- \`MODULE_MAP.md\` — module registry: path, pattern, DI, key classes, debt anchor
- Keep both in sync when adding a new module.
`;

// ── Embedded: hooks/settings.json ─────────────────────
const EMBEDDED_HOOKS_SETTINGS = `{
  "permissions": {
    "deny": [
      "Write(agent-artifacts/CLAUDE.md)",
      "Edit(agent-artifacts/CLAUDE.md)",
      "Write(agent-artifacts/spec-kit/**)",
      "Edit(agent-artifacts/spec-kit/**)",
      "Write(**/*.xcodeproj/**)",
      "Edit(**/*.xcodeproj/**)",
      "Write(**/*.xcworkspace/**)",
      "Edit(**/*.xcworkspace/**)",
      "Write(**/BuildConfig.java)",
      "Edit(**/BuildConfig.java)",
      "Write(**/R.java)",
      "Edit(**/R.java)",
      "Write(**/*.generated.kt)",
      "Edit(**/*.generated.kt)",
      "Write(**/build/**)",
      "Edit(**/build/**)",
      "Write(**/gradlew)",
      "Edit(**/gradlew)",
      "Write(**/gradlew.bat)",
      "Edit(**/gradlew.bat)"
    ]
  },
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/scripts/protected-paths.sh"
          }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/scripts/lint-gate.sh"
          }
        ]
      }
    ],
    "Stop": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/scripts/done-gate.sh"
          }
        ]
      }
    ]
  }
}`;

// ── Embedded: hooks/scripts/protected-paths.sh ────────
const EMBEDDED_PROTECTED_PATHS_SH = `#!/usr/bin/env bash
# PreToolUse hook — blocks writes to generated/tool files that agents must never touch.

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', '') or
          data.get('tool_input', {}).get('path', ''))
except Exception:
    print('')
" 2>/dev/null)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

CLEAN="\${FILE_PATH#./}"

deny() {
  local reason="$1"
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"'"$reason"'"}}'
  exit 0
}

# ── Artifacts protection ──────────────────────────────────────────────────────
[[ "$CLEAN" == agent-artifacts/CLAUDE.md ]]        && deny "agent-artifacts/CLAUDE.md is a read-only snapshot — re-run the setup wizard to update it."
[[ "$CLEAN" == agent-artifacts/spec-kit/* ]]       && deny "spec-kit/ files are read-only — re-run the wizard to regenerate AI artifacts, or edit human-authored specs directly."

# ── iOS generated / project files ────────────────────────────────────────────
[[ "$CLEAN" == *.xcodeproj/* || "$CLEAN" == *.xcodeproj ]] && deny "Xcode project files are managed by Xcode — do not modify programmatically."
[[ "$CLEAN" == *.xcworkspace/* || "$CLEAN" == *.xcworkspace ]] && deny "Xcode workspace files are managed by Xcode — do not modify programmatically."

# ── Android generated files ───────────────────────────────────────────────────
[[ "$CLEAN" == */BuildConfig.java ]]       && deny "BuildConfig.java is auto-generated by Gradle — edit build.gradle instead."
[[ "$CLEAN" == */R.java ]]                 && deny "R.java is auto-generated by AAPT — edit resource XML files instead."
[[ "$CLEAN" == *.generated.kt ]]           && deny "*.generated.kt files are auto-generated — do not modify directly."
[[ "$CLEAN" == **/gradlew || "$CLEAN" == gradlew ]] && deny "gradlew is auto-generated — do not modify."
[[ "$CLEAN" == **/gradlew.bat || "$CLEAN" == gradlew.bat ]] && deny "gradlew.bat is auto-generated — do not modify."

# ── Build output directories ──────────────────────────────────────────────────
[[ "$CLEAN" == */build/* || "$CLEAN" == build/* ]] && deny "build/ is a generated output directory — do not write files here."
[[ "$CLEAN" == DerivedData/* || "$CLEAN" == */DerivedData/* ]] && deny "DerivedData/ is Xcode's build cache — do not write files here."

exit 0
`;

// ── Embedded: hooks/scripts/lint-gate.sh ──────────────
const EMBEDDED_LINT_GATE_SH = `#!/usr/bin/env bash
# PostToolUse hook — runs a fast lint check after the agent edits a source file.

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', '') or
          data.get('tool_input', {}).get('path', ''))
except Exception:
    print('')
" 2>/dev/null)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

if [ -z "$PLATFORM" ]; then
  if [ -f "gradlew" ] || find . -maxdepth 3 -name "*.gradle" -o -name "*.gradle.kts" 2>/dev/null | grep -q .; then
    PLATFORM="android"
  elif find . -maxdepth 3 -name "*.xcodeproj" -type d 2>/dev/null | grep -q .; then
    PLATFORM="ios"
  else
    PLATFORM="none"
  fi
fi

if [[ "$PLATFORM" == "android" && "$FILE_PATH" == *.kt ]]; then
  if command -v ktlint &>/dev/null; then
    ktlint --editorconfig=".editorconfig" "$FILE_PATH" 2>&1
    STATUS=$?
    if [ $STATUS -ne 0 ]; then
      echo "❌ ktlint failed on $FILE_PATH — fix the formatting issues above before continuing." >&2
      exit $STATUS
    fi
  elif [ -f "gradlew" ]; then
    MODULE=$(echo "$FILE_PATH" | sed 's|/src/.*||' | sed 's|^\./||' | sed 's|/|:|g')
    ./gradlew ":$\{MODULE\}:ktlintCheck" --quiet 2>&1 | tail -20
    STATUS=\${PIPESTATUS[0]}
    if [ $STATUS -ne 0 ]; then
      echo "❌ ktlint check failed — run './gradlew ktlintFormat' to auto-fix." >&2
      exit $STATUS
    fi
  fi
fi

if [[ "$PLATFORM" == "ios" && "$FILE_PATH" == *.swift ]]; then
  if command -v swiftlint &>/dev/null; then
    swiftlint lint --quiet --path "$FILE_PATH" 2>&1
    STATUS=$?
    if [ $STATUS -ne 0 ]; then
      echo "❌ SwiftLint failed on $FILE_PATH — fix the violations above before continuing." >&2
      exit $STATUS
    fi
  fi
fi

exit 0
`;

// ── Embedded: hooks/scripts/done-gate.sh ──────────────
const EMBEDDED_DONE_GATE_SH = `#!/usr/bin/env bash
# Stop hook — runs when the agent finishes its turn.
# Checks that the agent didn't sneak edits into protected files.

VIOLATIONS=()

if git rev-parse --git-dir &>/dev/null; then
  MODIFIED=$(git diff --name-only 2>/dev/null; git diff --cached --name-only 2>/dev/null)

  while IFS= read -r f; do
    [ -z "$f" ] && continue
    case "$f" in
      agent-artifacts/CLAUDE.md)
        VIOLATIONS+=("PROTECTED (read-only snapshot): $f") ;;
      agent-artifacts/spec-kit/ARCHITECTURE.md|\
      agent-artifacts/spec-kit/MODULE_MAP.md|\
      agent-artifacts/spec-kit/DATA_MODEL.md)
        VIOLATIONS+=("PROTECTED (AI artifact — re-run wizard): $f") ;;
    esac
  done <<< "$MODIFIED"
fi

if [ \${#VIOLATIONS[@]} -gt 0 ]; then
  echo ""
  echo "⚠️  Done-gate warning: the agent modified protected files."
  echo "   These changes should NOT be committed. Review and revert if unintended:"
  for v in "\${VIOLATIONS[@]}"; do
    echo "   • $v"
  done
  echo ""
  echo "   Reminder:"
  echo "   • agent-artifacts/CLAUDE.md → re-run the setup wizard to update"
  echo "   • spec-kit/ARCHITECTURE.md, MODULE_MAP.md, DATA_MODEL.md → regenerate via wizard step"
  echo ""
fi

exit 0
`;

// ══════════════════════════════════════════════════════
//  INFO BUTTON HELPERS
// ══════════════════════════════════════════════════════
function toggleInfo(btn) {
  const box = btn.nextElementSibling;
  if (box && box.classList.contains('info-box')) {
    box.classList.toggle('open');
    btn.style.borderColor = box.classList.contains('open') ? 'var(--accent)' : '';
    btn.style.color       = box.classList.contains('open') ? 'var(--accent)' : '';
  }
}
// Renders an (i) button + hidden info box as a pair.
// Usage: ${infoBtn('Your explanation here')}
function infoBtn(html) {
  return `<button class="info-btn" onclick="toggleInfo(this)" title="More info">i</button><div class="info-box">${html}</div>`;
}

// Renders a tier badge — Core / Recommended / Optional
function tierBadge(tier) {
  const label = { core: 'Core', recommended: 'Recommended', optional: 'Optional' }[tier] || tier;
  return `<span class="tier-badge ${tier}">${label}</span>`;
}

// ══════════════════════════════════════════════════════
//  STATE
// ══════════════════════════════════════════════════════
const state = {
  dirHandle: null,           // Project root — readwrite. Wizard reads Gradle from here, writes to agent-sdd/ subdirectory.
  saved: {},
  current: 'welcome',
  detectedInterceptors: [],  // OkHttp Interceptor class names found in source tree
  detectedModuleDetails: [], // [{name, type, diCol, notes}] from settings.gradle + each module's build.gradle
};

// ══════════════════════════════════════════════════════
//  COMPANION  (Option B — local claude CLI bridge)
//  node agent-sdd/companion.js  →  http://localhost:7842
// ══════════════════════════════════════════════════════
const COMPANION_URL    = 'http://localhost:7842';
let   companionReady   = false;
let   companionPollTimer = null;

async function pollCompanion() {
  try {
    const r = await fetch(COMPANION_URL + '/health', { signal: AbortSignal.timeout(1500) });
    if (r.ok) {
      const data = await r.json();
      // Check whether the companion's project matches the wizard's selected folder.
      // The browser can't give us the full path, but we can compare folder names.
      const selectedName   = state.dirHandle?.name || null;
      const companionName  = data.projectName || null;
      const mismatch       = selectedName && companionName && selectedName !== companionName;
      setCompanionStatus(true, data.projectRoot, mismatch ? { selected: selectedName, companion: companionName } : null);
      return;
    }
  } catch (_) { /* not running */ }
  setCompanionStatus(false);
}

function setCompanionStatus(connected, projectRoot, mismatch) {
  // mismatch = null (ok) | { selected, companion } (folder names differ)
  companionReady = connected && !mismatch;
  const dot   = document.getElementById('companionDot');
  const label = document.getElementById('companionLabel');
  if (!dot || !label) return;

  if (connected && mismatch) {
    dot.className     = 'companion-dot connecting';   // amber = warning
    label.textContent = '⚠ Companion';
    label.className   = 'companion-label';
    label.style.color = '#fbbf24';
    label.title       = `Companion project: "${mismatch.companion}"\nWizard project: "${mismatch.selected}"\n\nThey don't match. Run the companion from inside your selected project:\n  node agent-sdd/companion.js\nor pass the path explicitly:\n  node /path/to/agent-sdd/companion.js --project /path/to/${mismatch.selected}`;
  } else if (connected) {
    dot.className     = 'companion-dot connected';
    label.textContent = '● Companion';
    label.className   = 'companion-label connected';
    label.style.color = '';
    label.title       = 'SDD Companion running — project: ' + (projectRoot || '?');
  } else {
    dot.className     = 'companion-dot';
    label.textContent = 'Companion';
    label.className   = 'companion-label';
    label.style.color = '';
    label.title       = 'Companion not running.\nStart it from your project root:\n  node agent-sdd/companion.js';
  }

  // Refresh run-button state and hint if task screen is visible
  const btn  = document.getElementById('btnRunClaude');
  const hint = document.getElementById('companionHint');
  if (btn) {
    btn.disabled = !companionReady;
    if (!connected) {
      btn.title = 'Start the companion first:\n  node agent-sdd/companion.js';
    } else if (mismatch) {
      btn.title = `Companion is pointed at "${mismatch.companion}" but wizard has "${mismatch.selected}" selected — fix the mismatch first`;
    } else {
      btn.title = 'Run this task with Claude Code CLI';
    }
  }
  if (hint) {
    if (!connected) {
      hint.innerHTML = 'Start the companion from your project root: <code style="font-size:10px;background:var(--surface2);padding:2px 6px;border-radius:3px;border:1px solid var(--border)">node agent-sdd/companion.js</code>';
      hint.style.display = '';
    } else if (mismatch) {
      hint.innerHTML = `⚠ Companion is serving <strong>${mismatch.companion}</strong> but you selected <strong>${mismatch.selected}</strong>. Run companion from inside the selected project.`;
      hint.style.color  = '#fbbf24';
      hint.style.display = '';
    } else {
      hint.style.display = 'none';
    }
  }
}

function startCompanionPolling() {
  pollCompanion();
  companionPollTimer = setInterval(pollCompanion, 5000);
}

async function runWithClaude() {
  const id = document.getElementById('task-id')?.value.trim();
  if (!id) { showToast('Enter a Ticket ID first', 'error'); return; }

  if (!companionReady) {
    showToast('Companion not ready — check the ⚠ indicator in the header', 'error');
    return;
  }

  // Auto-save task before running
  await saveTask();

  const taskPath = 'agent-artifacts/tasks/' + id + '.md';

  const terminal  = document.getElementById('claudeTerminal');
  const body      = document.getElementById('claudeTerminalBody');
  const spinner   = document.getElementById('terminalSpinner');
  const titleEl   = document.getElementById('terminalTitle');
  const runBtn    = document.getElementById('btnRunClaude');

  if (!terminal || !body) return;

  // Reset
  body.innerHTML = '';
  terminal.classList.add('visible');
  if (spinner) spinner.classList.add('active');
  if (titleEl) titleEl.textContent = 'Running ' + id + '…';
  if (runBtn)  { runBtn.disabled = true; runBtn.textContent = '⏳ Running…'; }
  terminal.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

  try {
    const res = await fetch(COMPANION_URL + '/run', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ taskPath }),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: 'Unknown error' }));
      appendTerminal(body, err.error || 'Request failed', 'err');
      if (spinner) spinner.classList.remove('active');
      if (titleEl) titleEl.textContent = 'Error';
      return;
    }

    const reader = res.body.getReader();
    const dec    = new TextDecoder();
    let   buf    = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });

      // Parse SSE lines from buffer
      const lines = buf.split('\n');
      buf = lines.pop(); // keep incomplete last line
      let event = null;
      for (const line of lines) {
        if (line.startsWith('event: '))       { event = line.slice(7).trim(); }
        else if (line.startsWith('data: ')) {
          try {
            const payload = JSON.parse(line.slice(6));
            if (event === 'chunk') {
              appendTerminal(body, payload.text, payload.stderr ? 'stderr' : '');
            } else if (event === 'done') {
              const code = payload.exitCode ?? 0;
              if (spinner) spinner.classList.remove('active');
              if (titleEl) titleEl.textContent = code === 0 ? id + ' — Done ✅' : id + ' — Exited ' + code;
              appendTerminal(body, code === 0 ? '✅ Completed (exit 0)' : '⚠ Exited with code ' + code, 'done');
            } else if (event === 'error') {
              appendTerminal(body, payload.message || 'Unknown error', 'err');
              if (spinner) spinner.classList.remove('active');
              if (titleEl) titleEl.textContent = 'Error';
            }
          } catch (_) { /* malformed JSON — skip */ }
          event = null;
        }
      }

      // Auto-scroll terminal
      body.scrollTop = body.scrollHeight;
    }
  } catch (err) {
    appendTerminal(body, 'Connection failed: ' + err.message, 'err');
    if (spinner) spinner.classList.remove('active');
    if (titleEl) titleEl.textContent = 'Connection error';
  } finally {
    if (runBtn) { runBtn.disabled = !companionReady; runBtn.textContent = '▶ Run with Claude'; }
  }
}

function appendTerminal(body, text, type) {
  if (!body || !text) return;
  const span = document.createElement('span');
  span.className = type === 'stderr' ? 't-stderr' : type === 'done' ? 't-done' : type === 'err' ? 't-err' : '';
  span.textContent = text;
  body.appendChild(span);
  body.scrollTop = body.scrollHeight;
}

const STEPS = [
  { id: 'welcome', icon: '👋', label: 'Welcome', file: null },
  { id: 'done',    icon: '✅', label: 'Done',    file: null },
];

// Maps each wizard step ID → contextual tutorial anchor.
// These are relative paths so they resolve correctly from any local directory.
const STEP_TUTORIALS = {
  projectconfig: 'tutorial.html#setup',
  architecture:  'tutorial-spec-kit.html#architecture',
  conventions:   'tutorial-spec-kit.html#conventions',
  migrations:    'tutorial-spec-kit.html#migrations',
  modules:       'tutorial-spec-kit.html#modulemap',
  debt:          'tutorial-spec-kit.html#techdebt',
  testing:       'tutorial-spec-kit.html#testing',
  datamodel:     'tutorial-spec-kit.html#datamodel',
};

// ══════════════════════════════════════════════════════
//  SIDEBAR
// ══════════════════════════════════════════════════════
function buildSidebar() {
  const container = document.getElementById('sidebarSteps');
  container.innerHTML = STEPS.map(s => `
    <div class="step-item ${s.id === state.current ? 'active' : ''} ${state.saved[s.id] ? 'done' : ''}"
         id="nav-${s.id}" onclick="goTo('${s.id}')">
      <span class="step-icon">${state.saved[s.id] ? '✅' : s.icon}</span>
      <div>
        <div class="step-label">${s.label}</div>
        ${s.file ? `<div class="step-file">${s.file}</div>` : ''}
        ${s.artifact ? `<div class="step-artifact-badge">⚡ AI artifact</div>` : ''}
      </div>
    </div>
  `).join('');
}

function goTo(id) {
  state.current = id;
  document.querySelectorAll('.step-screen').forEach(s => s.classList.remove('active'));
  const screen = document.getElementById('screen-' + id);
  if (screen) screen.classList.add('active');
  // Always return to the top of the form panel when switching pages.
  const fp = document.querySelector('.form-panel');
  if (fp) fp.scrollTop = 0;
  buildSidebar();
  const step = STEPS.find(s => s.id === id);
  document.getElementById('headerTitle').textContent = step.label;
  document.getElementById('headerDesc').textContent = step.file
    ? (step.artifact ? `⚡ AI artifact — ${step.file}` : `📝 Human-authored — ${step.file}`)
    : (id === 'welcome' ? "Set up your project's SDD skeleton" : 'All spec-kit files generated!');

  // Show contextual tutorial link if this step has one
  const tutLink = document.getElementById('headerTutorial');
  if (tutLink) {
    const tutUrl = STEP_TUTORIALS[id];
    if (tutUrl) {
      tutLink.href = tutUrl;
      tutLink.style.display = 'inline-flex';
    } else {
      tutLink.style.display = 'none';
    }
  }
  // Auto-fill conv-package from cfg-package if not already set
  if (id === 'conventions') {
    const src = document.getElementById('cfg-package')?.value.trim();
    const dst = document.getElementById('conv-package');
    if (dst && !dst.value && src) dst.value = src;
  }
  if (step.file) {
    updatePreview(id);
    document.getElementById('previewPanel').classList.remove('collapsed');
  } else {
    document.getElementById('previewPanel').classList.add('collapsed');
  }
}

// ══════════════════════════════════════════════════════
//  DRAFT PERSISTENCE  (localStorage)
//  Saves every form change so a page refresh never loses work.
//  Cleared field-by-field only when the user explicitly saves a step.
// ══════════════════════════════════════════════════════

const DRAFT_KEY = 'sdd-wizard-draft';

// Snapshot all current form values + selected pills → localStorage.
let _draftTimer = null;
function saveDraft() {
  clearTimeout(_draftTimer);
  _draftTimer = setTimeout(() => {
    const draft = { fields: {}, pills: {} };

    // All text inputs and textareas that carry an id
    // Skip task-* fields — task form always starts blank (no pre-fill across sessions)
    document.querySelectorAll('input[id]:not([type="checkbox"]):not([type="radio"]), textarea[id]').forEach(el => {
      if (el.id.startsWith('task-')) return;
      draft.fields[el.id] = el.value;
    });

    // Checkbox states — used by task quality gate toggles
    // Skip task-* fields for the same reason
    document.querySelectorAll('input[id][type="checkbox"]').forEach(el => {
      if (el.id.startsWith('task-')) return;
      draft.fields[el.id] = el.checked;
    });

    // Selected pills — keyed by group name (from the input's name attribute)
    // Skip task-* pill groups — task form always starts blank
    document.querySelectorAll('[id^="pill-"].selected input').forEach(input => {
      const group = input.name;
      if (group.startsWith('task-')) return;
      if (!draft.pills[group]) draft.pills[group] = [];
      draft.pills[group].push(input.value);
    });

    localStorage.setItem(DRAFT_KEY, JSON.stringify(draft));
  }, 300); // debounce — don't thrash storage on every keystroke
}

// Read the draft value for a specific field id (used by renderApproachRows
// to pre-fill cards whose textareas don't exist in the DOM yet).
function getDraftField(fieldId) {
  try {
    const draft = JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}');
    return draft.fields?.[fieldId] ?? '';
  } catch { return ''; }
}

// Restore all saved draft values into the DOM.
// Called once after all screens are built.
function restoreDraft() {
  let draft;
  try { draft = JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}'); }
  catch { return; }
  if (!draft.fields && !draft.pills) return;

  // ── Restore plain text/number fields and checkbox states ─────────────────
  Object.entries(draft.fields || {}).forEach(([id, value]) => {
    if (id.startsWith('approach-')) return;
    const el = document.getElementById(id);
    if (!el) return;
    if (typeof value === 'boolean') {
      if (el.type === 'checkbox') el.checked = value;
    } else {
      el.value = value;
    }
  });

  // ── Restore pill selections ────────────────────────────────────────────────
  Object.entries(draft.pills || {}).forEach(([group, values]) => {
    values.forEach(value => {
      const pill = document.getElementById(`pill-${group}_${value}`);
      if (!pill) return;
      const input = pill.querySelector('input');
      if (input?.type === 'radio') {
        // Deselect siblings before selecting this one
        document.querySelectorAll(`[id^="pill-${group}_"]`).forEach(p => p.classList.remove('selected'));
      }
      pill.classList.add('selected');
      if (input) input.checked = true;
      // Show "Other" expand span if this is an Other pill
      if (value === '__other__') {
        const expand = pill.querySelector('.other-expand');
        if (expand) expand.style.display = 'inline';
      }
    });
  });

  // ── Restore which steps were already saved (sidebar ✅) ───────────────────
  (draft.savedSteps || []).forEach(stepId => { state.saved[stepId] = true; });

  // ── Platform-specific post-restore hooks ──────────────────────────────────
  PLATFORM.onDraftRestored?.();

  updatePreview(state.current);
}

// Mark a step as committed — store the saved step ids in the draft so that
// after a refresh the sidebar can show ✅ for already-saved steps.
function markDraftSaved(stepId) {
  try {
    const draft = JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}');
    if (!draft.savedSteps) draft.savedSteps = [];
    if (!draft.savedSteps.includes(stepId)) draft.savedSteps.push(stepId);
    localStorage.setItem(DRAFT_KEY, JSON.stringify(draft));
  } catch { /* ignore */ }
}

// Hook: attach saveDraft to all input/change events on a screen element.
// Called once per screen after it is built.
function attachDraftListeners(screenId) {
  const screen = document.getElementById(screenId);
  if (!screen) return;
  screen.addEventListener('input',  saveDraft);
  screen.addEventListener('change', saveDraft);
}

// ══════════════════════════════════════════════════════
//  BROWSER COMPATIBILITY
// ══════════════════════════════════════════════════════
const hasFSA = 'showDirectoryPicker' in window;

// Show a warning banner when File System Access API is unavailable (Safari, Firefox).
// Called once after DOMContentLoaded — banner is hidden by default in HTML.
function applyBrowserCompat() {
  if (!hasFSA) {
    const banner = document.getElementById('safariBanner');
    if (banner) banner.style.display = 'block';
    // Grey out the Select button tooltip
    const selectBtn = document.querySelector('button[onclick="grantFolder()"]');
    if (selectBtn) selectBtn.title = 'Direct folder access not supported in this browser — files will download to your Downloads folder instead.';
  }
}

// ══════════════════════════════════════════════════════
//  FILE SYSTEM ACCESS API
// ══════════════════════════════════════════════════════
async function grantFolder() {
  if (!hasFSA) {
    showToast('Direct folder access is not supported in Safari or Firefox — files will download to your Downloads folder when you save each step.', 'info');
    return;
  }
  try {
    const handle = await window.showDirectoryPicker();
    state.dirHandle = handle;
    const badge = document.getElementById('sddBadge');
    badge.textContent = '📂 ' + handle.name;
    badge.className = 'folder-badge granted';
    showToast('Project folder set: ' + handle.name + ' — analysing…', 'success');

    // Auto-set codebase_path to '..' — always correct when agent-artifacts/ is inside project root
    const pathEl = document.getElementById('cfg-codebase-path');
    if (pathEl && !pathEl.value) pathEl.value = '..';

    // Try to load existing agent-artifacts/project.config.md and pre-fill the form
    const existing = await tryReadFile(handle, 'agent-artifacts', 'project.config.md');
    if (existing) loadExistingConfig(existing);

    // Platform hook — e.g. analyzeProject()
    PLATFORM.onFolderGranted?.();

    // Light up sidebar ✅ for any steps whose output files already exist
    detectExistingOutputFiles(handle);
  } catch (e) {
    if (e.name !== 'AbortError') showToast('Could not access folder — try selecting the folder again.', 'error');
  }
}

// ── Detect already-saved output files and light up sidebar ✅ ─────────────────
// Called after a project folder is selected. For each step that has an output
// file, checks whether agent-artifacts/<file> already exists. If it does, marks
// state.saved so the sidebar shows ✅ without the user re-running that step.
async function detectExistingOutputFiles(handle) {
  if (!handle) return;

  let completedCount = 0;
  const contentSteps = STEPS.filter(s => s.file);

  await Promise.all(contentSteps.map(async step => {
    const parts = step.file.split('/');    // e.g. 'spec-kit/ARCHITECTURE.md' → ['spec-kit','ARCHITECTURE.md']
    const content = await tryReadFile(handle, 'agent-artifacts', ...parts);
    if (content) {
      state.saved[step.id] = true;
      completedCount++;
    }
  }));

  buildSidebar();

  if (completedCount === 0) return;

  // Update or inject the setup-status banner on the welcome screen
  const allDone = completedCount === contentSteps.length;
  showSetupBanner(completedCount, contentSteps.length, allDone);
}

function showSetupBanner(done, total, allDone) {
  // Remove any existing banner first
  document.getElementById('setupStatusBanner')?.remove();

  const welcome = document.getElementById('screen-welcome');
  if (!welcome) return;

  const banner = document.createElement('div');
  banner.id = 'setupStatusBanner';

  if (allDone) {
    banner.style.cssText = 'background:rgba(74,222,128,0.08);border:1px solid rgba(74,222,128,0.3);border-radius:var(--radius);padding:14px 18px;margin-bottom:20px;display:flex;align-items:center;gap:12px';
    banner.innerHTML = `
      <span style="font-size:22px">✅</span>
      <div>
        <div style="font-size:13px;font-weight:600;color:#4ade80">Setup already complete for this project</div>
        <div style="font-size:11px;color:var(--text-muted);margin-top:3px">All ${total} spec-kit files found in <code>agent-artifacts/</code>. You can jump to any step to review or update a file — no need to redo the whole setup.</div>
      </div>`;
  } else {
    banner.style.cssText = 'background:rgba(251,191,36,0.08);border:1px solid rgba(251,191,36,0.3);border-radius:var(--radius);padding:14px 18px;margin-bottom:20px;display:flex;align-items:center;gap:12px';
    banner.innerHTML = `
      <span style="font-size:22px">⚠️</span>
      <div>
        <div style="font-size:13px;font-weight:600;color:#fbbf24">Partial setup detected (${done}/${total} steps)</div>
        <div style="font-size:11px;color:var(--text-muted);margin-top:3px">Some spec-kit files are missing. Steps marked ✅ in the sidebar are already saved — continue from where you left off.</div>
      </div>`;
  }

  // Insert at the top of the welcome screen content
  const hero = welcome.querySelector('.welcome-hero');
  if (hero) hero.insertBefore(banner, hero.firstChild);
  else welcome.insertBefore(banner, welcome.firstChild);
}

function loadExistingConfig(text) {
  const get = key => text.match(new RegExp(`^${key}:\\s*(.+)`, 'm'))?.[1]?.trim() ?? '';

  // Generic fields
  const codebasePath = get('codebase_path');
  const setVal = (id, val) => { const el = document.getElementById(id); if (el && val) el.value = val; };
  setVal('cfg-codebase-path', codebasePath);

  // Delegate Android-specific field restore to platform
  PLATFORM.onConfigLoaded?.(text);
}

// ══════════════════════════════════════════════════════
//  GENERIC FILE UTILITIES
// ══════════════════════════════════════════════════════
async function tryReadFile(dirHandle, ...parts) {
  try {
    let dir = dirHandle;
    for (let i = 0; i < parts.length - 1; i++) dir = await dir.getDirectoryHandle(parts[i]);
    const fh = await dir.getFileHandle(parts[parts.length - 1]);
    return await (await fh.getFile()).text();
  } catch { return null; }
}

async function countSourceFiles(dirHandle, maxDepth = 4) {
  const counts = { kt: 0, java: 0 };
  async function walk(dh, depth) {
    if (depth <= 0) return;
    try {
      for await (const [name, handle] of dh) {
        if (handle.kind === 'file') {
          if (name.endsWith('.kt')) counts.kt++;
          else if (name.endsWith('.java')) counts.java++;
        } else if (handle.kind === 'directory' && !['build', '.gradle', '.git', 'node_modules'].includes(name)) {
          await walk(handle, depth - 1);
        }
      }
    } catch {}
  }
  await walk(dirHandle, maxDepth);
  return counts;
}

async function saveFile(relativePath, content) {
  if (!state.dirHandle) { showToast('Select a project folder first', 'error'); return false; }
  try {
    // Support both: project root selected (agent-artifacts/ created inside) or agent-artifacts/ selected directly.
    const sddDir = state.dirHandle.name === 'agent-artifacts'
      ? state.dirHandle
      : await state.dirHandle.getDirectoryHandle('agent-artifacts', { create: true });

    const parts = relativePath.split('/');
    let dir = sddDir;
    for (let i = 0; i < parts.length - 1; i++) {
      dir = await dir.getDirectoryHandle(parts[i], { create: true });
    }
    const fileHandle = await dir.getFileHandle(parts[parts.length - 1], { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(content);
    await writable.close();
    return true;
  } catch (e) {
    console.error(e);
    return false;
  }
}

// Called when final wizard step is saved — creates the complete agent-artifacts structure
async function createCompleteArtifactsStructure() {
  if (!state.dirHandle || !hasFSA) return;

  console.log('🚀 Creating complete agent-artifacts structure...');
  const results = [];

  // Helper to track results
  const write = async (path, content) => {
    const ok = await saveFile(path, content);
    results.push({ path, ok });
    console.log(ok ? `  ✅ ${path}` : `  ❌ ${path}`);
    return ok;
  };

  // ── CLAUDE.md ─────────────────────────────────────────
  await write('CLAUDE.md', EMBEDDED_CLAUDE_MD);

  // ── tasks/ ────────────────────────────────────────────
  await write('tasks/TASK_TEMPLATE.md',      EMBEDDED_TASK_TEMPLATE);
  await write('tasks/BOOTSTRAP_TEMPLATE.md', EMBEDDED_BOOTSTRAP_TEMPLATE);

  // ── context/ ──────────────────────────────────────────
  await write('context/TEMPLATE.md', EMBEDDED_CONTEXT_TEMPLATE);
  await write('context/_index.md',   EMBEDDED_CONTEXT_INDEX);

  // ── hooks/ staged inside agent-artifacts/ ─────────────
  // Browser FSA cannot create hidden folders (.claude/) directly.
  // Files are staged here; user runs one command to install them.
  await write('hooks/settings.json',              EMBEDDED_HOOKS_SETTINGS);
  await write('hooks/scripts/protected-paths.sh', EMBEDDED_PROTECTED_PATHS_SH);
  await write('hooks/scripts/lint-gate.sh',       EMBEDDED_LINT_GATE_SH);
  await write('hooks/scripts/done-gate.sh',       EMBEDDED_DONE_GATE_SH);

  const failed = results.filter(r => !r.ok);
  const succeeded = results.filter(r => r.ok).length;

  if (failed.length === 0) {
    showToast('✅ Setup complete! All agent-artifacts files created.', 'success');
  } else {
    showToast(`⚠️  Setup complete with ${failed.length} skipped file(s) — check console`, 'info');
  }

  console.log(`🏁 Done. ${succeeded}/${results.length} files created.`);
  console.log('');
  console.log('📌 Final step — install Claude Code hooks from your project terminal:');
  console.log('   cp -r agent-artifacts/hooks/.  .claude/');
  console.log('   chmod +x .claude/scripts/*.sh');
  console.log('   git add .claude/ && git commit -m "Add Claude Code SDD hooks"');

}

function downloadFallback(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename.split('/').pop();
  a.click(); URL.revokeObjectURL(url);
}

async function handleSave(stepId, filename, content) {
  // No folder selected yet — prompt the user to pick one before saving
  if (hasFSA && !state.dirHandle) {
    showToast('Select your project root or agent-artifacts/ folder to save directly…', 'info');
    try {
      const handle = await window.showDirectoryPicker();
      state.dirHandle = handle;
      const badge = document.getElementById('sddBadge');
      if (badge) { badge.textContent = '📂 ' + handle.name; badge.className = 'folder-badge granted'; }
      showToast('Folder set: ' + handle.name + ' — saving…', 'success');
    } catch (e) {
      // User cancelled or picker failed — fall back to download
      downloadFallback(filename, content);
      showToast('No folder selected — file downloaded to Downloads instead', 'info');
      return;
    }
  }

  if (hasFSA && state.dirHandle) {
    const ok = await saveFile(filename, content);
    if (ok) {
      state.saved[stepId] = true;
      markDraftSaved(stepId);
      buildSidebar();
      showToast('Saved → ' + filename, 'success');
      updateDoneScreen();
    } else {
      showToast('Save failed — downloading instead', 'error');
      downloadFallback(filename, content);
    }
  } else {
    // Browser doesn't support FSA (Safari/Firefox) — download is the only option
    downloadFallback(filename, content);
    state.saved[stepId] = true;
    markDraftSaved(stepId);
    buildSidebar();
    showToast('Downloaded ' + filename.split('/').pop() + ' (use Chrome/Edge to save directly)', 'info');
    updateDoneScreen();
  }
}

// ══════════════════════════════════════════════════════
//  MARKDOWN RENDERER
// ══════════════════════════════════════════════════════
function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function inlineMd(text) {
  return escHtml(text)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code class="md-code">$1</code>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>');
}

function renderMarkdown(md) {
  // Protect fenced code blocks
  const blocks = [];
  md = md.replace(/```[^\n]*\n([\s\S]*?)```/g, (_, code) => {
    blocks.push(`<pre class="md-code-block">${escHtml(code.trimEnd())}</pre>`);
    return `\x00BLOCK${blocks.length - 1}\x00`;
  });

  const lines = md.split('\n');
  let html = '', inTable = false, tableHead = true, tableHtml = '', inList = false;

  const flushTable = () => { html += tableHtml + '</tbody></table>'; inTable = false; tableHead = true; tableHtml = ''; };
  const flushList  = () => { html += '</ul>'; inList = false; };

  for (const raw of lines) {
    const line = raw;

    // Code block placeholder
    if (/\x00BLOCK\d+\x00/.test(line)) {
      if (inList) flushList();
      if (inTable) flushTable();
      html += blocks[parseInt(line.match(/\d+/)[0])];
      continue;
    }

    // File header comment lines:  # ──── or # HUMAN-AUTHORED
    if (/^# /.test(line) && !/^#{2,}/.test(line)) {
      if (inList) flushList();
      if (inTable) flushTable();
      if (/^# [─═\-]{4,}/.test(line)) { html += '<hr class="md-hr">'; continue; }
      html += `<div class="md-comment">${escHtml(line.slice(2))}</div>`;
      continue;
    }

    // Headings
    const hm = line.match(/^(#{1,3}) (.+)/);
    if (hm) {
      if (inList) flushList();
      if (inTable) flushTable();
      const lvl = hm[1].length;
      html += `<div class="md-h${lvl}">${inlineMd(hm[2])}</div>`;
      continue;
    }

    // HR
    if (/^---+$/.test(line.trim())) {
      if (inList) flushList();
      if (inTable) flushTable();
      html += '<hr class="md-hr">';
      continue;
    }

    // Table row
    if (/^\|.+\|$/.test(line.trim())) {
      if (inList) flushList();
      const cells = line.trim().slice(1,-1).split('|').map(c => c.trim());
      if (cells.every(c => /^[-: ]+$/.test(c))) continue; // separator row
      if (!inTable) {
        inTable = true;
        tableHtml = '<table class="md-table"><thead><tr>' + cells.map(c => `<th>${inlineMd(c)}</th>`).join('') + '</tr></thead><tbody>';
        tableHead = false;
      } else {
        tableHtml += '<tr>' + cells.map(c => `<td>${inlineMd(c)}</td>`).join('') + '</tr>';
      }
      continue;
    } else if (inTable) { flushTable(); }

    // List item
    if (/^- /.test(line)) {
      if (!inList) { html += '<ul class="md-list">'; inList = true; }
      html += `<li>${inlineMd(line.slice(2))}</li>`;
      continue;
    } else if (inList) { flushList(); }

    // Empty line
    if (line.trim() === '') { html += '<div class="md-spacer"></div>'; continue; }

    // Paragraph
    html += `<p class="md-p">${inlineMd(line)}</p>`;
  }

  if (inList) flushList();
  if (inTable) flushTable();
  return html;
}

// ══════════════════════════════════════════════════════
//  UI HELPERS
// ══════════════════════════════════════════════════════
function showToast(msg, type = 'info') {
  const t = document.getElementById('toast');
  t.textContent = msg; t.className = 'show ' + type;
  setTimeout(() => { t.className = ''; }, 3000);
}

function togglePreview() {
  document.getElementById('previewPanel').classList.toggle('collapsed');
}

function showPreview(content) {
  document.getElementById('previewContent').innerHTML = renderMarkdown(content);
  document.getElementById('previewPanel').classList.remove('collapsed');
}

function esc(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function pill(name, value, group, type = 'check') {
  const id = group + '_' + value;
  return `<label class="${type}-pill" id="pill-${id}" onclick="event.preventDefault(); togglePill(this,'${group}','${value}','${type}')">
    <input type="${type === 'radio' ? 'radio' : 'checkbox'}" name="${group}" value="${value}">
    ${name}
  </label>`;
}

// "Other" pill — expands an inline text input when selected.
// Use for any pill group where a project might use a library not in the hardcoded list.
function otherPill(group, type = 'check') {
  const id = group + '___other__';
  return `<label class="${type}-pill other-pill" id="pill-${id}" onclick="event.preventDefault();toggleOtherPill(this,'${group}','${type}')">
    <input type="${type === 'radio' ? 'radio' : 'checkbox'}" name="${group}" value="__other__">
    Other<span class="other-expand" style="display:none">:&nbsp;<input type="text" class="other-text-input" id="other-input-${group}" placeholder="specify…" onclick="event.stopPropagation()" oninput="updatePreview(state.current);saveDraft()" style="border:none;background:transparent;outline:none;font:inherit;color:inherit;width:90px;margin-left:2px"></span>
  </label>`;
}

function togglePill(el, group, value, type) {
  if (type === 'radio') {
    document.querySelectorAll(`[id^="pill-${group}_"]`).forEach(p => p.classList.remove('selected'));
    el.classList.add('selected');
    el.querySelector('input').checked = true;
  } else {
    el.classList.toggle('selected');
    el.querySelector('input').checked = el.classList.contains('selected');
  }
  const step = STEPS.find(s => s.id === state.current);
  if (step && step.file) updatePreview(state.current);
  if (state.current === 'architecture') {
    if (group === 'async' || group === 'state') renderApproachRows(group);
    updateArchProgress();
  }
  saveDraft();
}

function toggleOtherPill(el, group, type) {
  togglePill(el, group, '__other__', type);
  const expand = el.querySelector('.other-expand');
  if (!expand) return;
  const selected = el.classList.contains('selected');
  expand.style.display = selected ? 'inline' : 'none';
  if (selected) el.querySelector('.other-text-input')?.focus();
}

function getPills(group) {
  return Array.from(document.querySelectorAll(`[id^="pill-${group}_"]`))
    .filter(p => p.classList.contains('selected'))
    .map(p => {
      const val = p.querySelector('input[type="checkbox"],input[type="radio"]').value;
      if (val === '__other__') {
        const txt = (document.getElementById(`other-input-${group}`)?.value || '').trim();
        return txt || null;
      }
      return val;
    })
    .filter(Boolean);
}

function getRadio(group) {
  const sel = document.querySelector(`[id^="pill-${group}_"].selected`);
  if (!sel) return '';
  const val = sel.querySelector('input').value;
  if (val === '__other__')
    return (document.getElementById(`other-input-${group}`)?.value || '').trim();
  return val;
}

// Selects a pill by value. If the value isn't in the hardcoded list, automatically
// selects "Other" and fills in the freeform text — used by analyzeProject().
function selectPill(group, value, type = 'check') {
  const el = document.getElementById(`pill-${group}_${value}`);
  if (el) {
    if (!el.classList.contains('selected')) togglePill(el, group, value, type);
    return;
  }
  // Value not in known pills — fall back to "Other"
  const otherEl = document.getElementById(`pill-${group}___other__`);
  if (otherEl && value) {
    if (!otherEl.classList.contains('selected')) toggleOtherPill(otherEl, group, type);
    const inp = document.getElementById(`other-input-${group}`);
    if (inp) { inp.value = value; updatePreview(state.current); saveDraft(); }
  }
}

// ══════════════════════════════════════════════════════
//  DONE SCREEN
// ══════════════════════════════════════════════════════
function updateDoneScreen() {
  const screen = document.getElementById('screen-done');
  if (!screen) return;
  const files = STEPS.filter(s => s.file);
  screen.querySelector('.done-files').innerHTML = files.map(s => `
    <div class="done-file">
      <div class="status-dot ${state.saved[s.id] ? '' : 'pending'}"></div>
      <span style="color:${state.saved[s.id] ? 'var(--success)' : 'var(--text-muted)'}">${s.file}</span>
    </div>
  `).join('');
}

function updatePreview(stepId) {
  const md = PLATFORM.generate[stepId]?.() ?? '';
  if (md) {
    document.getElementById('previewContent').innerHTML = renderMarkdown(md);
  }
}

async function saveStep(stepId) {
  const step = STEPS.find(s => s.id === stepId);
  if (!step || !step.file) return;

  // Warn before overwriting files that are manually maintained after first generation
  const protectedSteps = { modules: 'MODULE_MAP.md', datamodel: 'DATA_MODEL.md' };
  if (protectedSteps[stepId] && state.dirHandle) {
    const filename = protectedSteps[stepId];
    const exists   = await tryReadFile(state.dirHandle, 'agent-artifacts', 'spec-kit', filename)
                  ?? await tryReadFile(state.dirHandle, 'spec-kit', filename);
    if (exists) {
      const go = confirm(
        `⚠️  Overwrite ${filename}?\n\n` +
        `This file may contain manually added content (purposes, key classes, API contracts).\n\n` +
        `Saving will regenerate it from the wizard form only — anything added directly in the file will be lost.\n\n` +
        `Click OK to overwrite, or Cancel to keep the existing file.`
      );
      if (!go) return;
    }
  }

  const content = PLATFORM.generate[stepId]?.() ?? '';
  await handleSave(stepId, step.file, content);

  // Platform-specific extra saves (e.g. modules also writes context/_index.md)
  await PLATFORM.extraSave?.[stepId]?.();

  // When final step (datamodel) is saved, create the complete artifacts structure
  if (stepId === 'datamodel') {
    await createCompleteArtifactsStructure();
  }
}

// ══════════════════════════════════════════════════════
//  BOOTSTRAP
// ══════════════════════════════════════════════════════
function init() {
  // Populate STEPS from platform definition
  STEPS.length = 0;
  PLATFORM.steps.forEach(s => STEPS.push(s));

  const fp = document.getElementById('formPanel');

  // Welcome screen
  fp.innerHTML += `
  <div class="step-screen active" id="screen-welcome">
    <div class="welcome-hero">
      <h2>👋 Welcome to the SDD Setup Wizard</h2>
      <p>Fill in your project details step-by-step. Each step generates a <code>spec-kit/</code> file and saves it directly to your project folder.</p>

      <div style="background:var(--surface2);border:1px solid var(--border);border-radius:var(--radius);padding:20px;max-width:600px;margin:0 auto 28px;text-align:left">
        <div style="font-size:12px;font-weight:700;color:var(--accent);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:14px">How to run this tool</div>
        <div style="display:flex;flex-direction:column;gap:10px">
          ${[
            ['1','Open in Chrome or Edge','Double-click <code>setup-wizard.html</code>. File System Access API requires Chrome or Edge — other browsers will download files instead of saving directly.'],
            ['2','Select your project folder','Point to your project root (e.g. <code>MyApp/</code>). The wizard auto-detects your stack and writes all generated files into <code>agent-artifacts/</code> inside it.'],
            ['3','Fill in each step','Work through the sidebar steps left to right. Select your stack options, add modules and debt entries. The MD preview on the right updates live.'],
            ['4','Save each file','Click the green <strong>💾 Save</strong> button on each step. Files are written directly to <code>agent-artifacts/spec-kit/</code> inside the folder you selected. The sidebar shows ✅ for saved steps.'],
            ['5','Review the generated files','Open the saved <code>.md</code> files in your editor. Replace any <code>[fill in]</code> placeholders with your project-specific details.'],
            ['6','Run your first agent task','Copy <code>agent-sdd/tasks/TASK_TEMPLATE.md</code> to <code>agent-artifacts/tasks/</code>, fill in a real ticket, open a Claude session, and let the agent execute it.'],
          ].map(([n, title, desc]) => `
          <div style="display:flex;gap:12px;align-items:flex-start">
            <div style="background:var(--accent-dim);color:var(--accent);border-radius:50%;width:22px;height:22px;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;flex-shrink:0;margin-top:1px">${n}</div>
            <div>
              <div style="font-size:12px;font-weight:600;color:var(--text);margin-bottom:2px">${title}</div>
              <div style="font-size:11px;color:var(--text-muted);line-height:1.5">${desc}</div>
            </div>
          </div>`).join('')}
        </div>
      </div>

      <div style="font-size:12px;font-weight:600;color:var(--text-dim);margin-bottom:12px;text-transform:uppercase;letter-spacing:0.5px">What this wizard generates</div>
      <div class="welcome-steps">
        ${STEPS.filter(s=>s.file).map(s=>`
          <div class="welcome-step-card">
            <div class="num">${s.icon} ${s.who || 'Tech lead writes'}</div>
            <h4>${s.label}</h4>
            <div class="card-desc">${s.desc || ''}</div>
            <div class="step-file">${s.file}</div>
            ${s.critical ? `
            <details>
              <summary>What to get right</summary>
              <div class="detail-body">
                <div>
                  <div class="detail-section-title">Critical — agent depends on these</div>
                  <ul class="detail-list">
                    ${s.critical.map(c=>`<li>${c}</li>`).join('')}
                  </ul>
                </div>
                ${s.mistakes ? `
                <div>
                  <div class="detail-section-title warn">Common mistakes</div>
                  <ul class="detail-list mistakes">
                    ${s.mistakes.map(m=>`<li>${m}</li>`).join('')}
                  </ul>
                </div>` : ''}
              </div>
            </details>` : ''}
          </div>`).join('')}
      </div>
      <button class="btn btn-primary" onclick="goTo('projectconfig')">Start Setup →</button>
    </div>
  </div>`;

  // Done screen
  fp.innerHTML += `
  <div class="step-screen" id="screen-done">
    <div class="done-screen">
      <div class="check-big">🎉</div>
      <h2>Setup Complete!</h2>
      <p>All spec-kit files have been generated. Your SDD skeleton is ready. Fill in the remaining placeholder values in each file, then run your first task.</p>
      <div class="done-files"></div>
      <button class="btn btn-primary" onclick="goTo('welcome')">← Start Over</button>
    </div>
  </div>`;

  // Build platform-specific screens
  const stepIds = STEPS.filter(s => s.id !== 'welcome' && s.id !== 'done').map(s => s.id);
  stepIds.forEach(id => {
    PLATFORM.buildScreens[id]?.(fp);
  });

  // Build platform-agnostic task creation screen
  buildTaskScreen(fp);
  attachDraftListeners('screen-newtask');

  // Attach draft save listeners to every non-welcome, non-done screen
  stepIds.forEach(id => {
    attachDraftListeners('screen-' + id);
  });

  // Restore any previously saved draft (survives page refresh)
  restoreDraft();

  buildSidebar();
  updateDoneScreen();
}

// ══════════════════════════════════════════════════════
//  TASK SCREEN
//  Platform-agnostic task MD creation form.
//  Quality gate defaults come from PLATFORM.taskDefaults.
// ══════════════════════════════════════════════════════

function goToTaskScreen() {
  state.current = 'newtask';
  document.querySelectorAll('.step-screen').forEach(s => s.classList.remove('active'));
  document.getElementById('screen-newtask')?.classList.add('active');
  const fp = document.querySelector('.form-panel');
  if (fp) fp.scrollTop = 0;
  buildSidebar();
  document.getElementById('headerTitle').textContent = 'Create Task';
  document.getElementById('headerDesc').textContent = 'Generate a task MD file ready for Claude to execute';
  const tutLink = document.getElementById('headerTutorial');
  if (tutLink) { tutLink.href = 'tutorial.html#writing-tasks'; tutLink.style.display = 'inline-flex'; }
  document.getElementById('previewPanel').classList.remove('collapsed');
  updateTaskPreview();
  document.querySelectorAll('.tool-link').forEach(l => l.classList.remove('tool-active'));
  document.getElementById('tool-newtask')?.classList.add('tool-active');
}

function generateTaskMd() {
  const id    = document.getElementById('task-id')?.value.trim()    || '[PROJ]-1234';
  const title = document.getElementById('task-title')?.value.trim() || '[Title]';
  const type  = getRadio('task-type') || 'Feature';
  const desc  = document.getElementById('task-desc')?.value.trim()  || '[Description here]';

  const lines = id => (document.getElementById(id)?.value.trim() || '').split('\n').map(l => l.trim()).filter(Boolean);

  const criteria  = lines('task-criteria');
  const oos       = lines('task-oos');
  const areas     = document.getElementById('task-areas')?.value.trim() || '[Affected areas]';
  const testReq   = getRadio('task-test-req') || 'N';
  const testLevel = getRadio('task-level')    || 'Unit';
  const scenarios = lines('task-scenarios');
  const refs      = lines('task-refs');
  const notes     = document.getElementById('task-notes')?.value.trim();
  const qgCustom  = lines('task-qg-custom');

  const qgDefaults = (PLATFORM?.taskDefaults?.qualityGate || [])
    .filter(item => document.getElementById('task-qg-' + item.id)?.checked !== false)
    .map(item => `- [ ] ${item.label}`);
  const allQg = [...qgDefaults, ...qgCustom.map(l => `- [ ] ${l}`)];

  const types = ['Feature', 'Bug', 'Refactor', 'Task'];

  return `# Task: ${id} — ${title}

## Type

${types.map(t => `- [${t === type ? 'x' : ' '}] ${t}`).join('\n')}

## Description

${desc}

## Acceptance Criteria

${criteria.length ? criteria.map(c => `- [ ] ${c}`).join('\n') : '- [ ] [Criterion 1]'}

## Quality Gate

${allQg.length ? allQg.join('\n') : '- [ ] [Add quality gate items]'}

## Out of Scope

${oos.length ? oos.map(o => `- ${o}`).join('\n') : '- [None]'}

## Affected Areas

${areas}

## Testing

Required: ${testReq}

Level: ${testLevel}

Scenarios:
${scenarios.length ? scenarios.map(s => `- [ ] ${s}`).join('\n') : '- [ ] [Scenario 1]'}

## Designs / References

${refs.length ? refs.map(r => `- ${r}`).join('\n') : '- None'}

## Notes

${notes || '[Notes here or remove section]'}
`;
}

function updateTaskPreview() {
  if (state.current !== 'newtask') return;
  document.getElementById('previewContent').innerHTML = renderMarkdown(generateTaskMd());
}

async function saveTask() {
  const id = document.getElementById('task-id')?.value.trim();
  if (!id) { showToast('Enter a Ticket ID first', 'error'); return; }
  await handleSave('newtask-' + id, 'tasks/' + id + '.md', generateTaskMd());
}

function resetTaskForm() {
  ['task-id','task-title','task-desc','task-criteria','task-qg-custom',
   'task-oos','task-areas','task-scenarios','task-refs','task-notes'].forEach(fid => {
    const el = document.getElementById(fid);
    if (el) el.value = '';
  });
  ['task-type','task-test-req','task-level'].forEach(group => {
    document.querySelectorAll(`[id^="pill-${group}_"]`).forEach(p => {
      p.classList.remove('selected');
      const inp = p.querySelector('input');
      if (inp) inp.checked = false;
    });
  });
  (PLATFORM?.taskDefaults?.qualityGate || []).forEach(item => {
    const el = document.getElementById('task-qg-' + item.id);
    if (el) el.checked = true;
  });
  updateTaskPreview();
  showToast('Form cleared — ready for next task', 'info');
}

function buildTaskScreen(fp) {
  const qgItems = PLATFORM?.taskDefaults?.qualityGate || [];
  fp.innerHTML += `
  <div class="step-screen" id="screen-newtask">
    <div style="max-width:700px">

      <div class="form-section">
        <h3>Ticket</h3>
        <div style="display:flex;gap:12px">
          <div class="form-row" style="width:160px;flex-shrink:0;margin-bottom:0">
            <label>Ticket ID</label>
            <input type="text" id="task-id" placeholder="[PROJ]-1234" oninput="updateTaskPreview();saveDraft()">
          </div>
          <div class="form-row" style="flex:1;margin-bottom:0">
            <label>Title</label>
            <input type="text" id="task-title" placeholder="Short descriptive title" oninput="updateTaskPreview();saveDraft()">
          </div>
        </div>
        <div class="form-row" style="margin-top:12px">
          <label>Type</label>
          <div class="radio-group">
            ${['Feature','Bug','Refactor','Task'].map(t => pill(t, t, 'task-type', 'radio')).join('')}
          </div>
        </div>
      </div>

      <div class="form-section">
        <h3>Description</h3>
        <div class="form-row">
          <label>What needs to be done and why — 1–5 sentences, specific about what changes</label>
          <textarea id="task-desc" rows="4"
            placeholder="e.g. Add a store_selected Firebase event fired when the user taps a store. The event must include store_id as a property."
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="form-section">
        <h3>Acceptance Criteria</h3>
        <div class="form-row">
          <label>One criterion per line — each must be verifiable by a specific file, function, or test</label>
          <textarea id="task-criteria" rows="5"
            placeholder="TrackStoreSelectedEvent is called in SelectStoreFragment.onStoreClicked() with the correct store_id&#10;Event is NOT sent to Adjust — Firebase only&#10;Unit test covers success and cancellation paths"
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="form-section">
        <h3>Quality Gate</h3>
        <p class="form-sub">Platform defaults — uncheck any that don't apply to this task</p>
        <div style="background:var(--surface2);border:1px solid var(--border);border-radius:var(--radius);padding:4px 14px;margin-bottom:12px">
          ${qgItems.map(item => `
          <div class="toggle-row">
            <div class="toggle-label" style="font-size:12px;flex:1;padding-right:12px">${item.label}</div>
            <label class="toggle">
              <input type="checkbox" id="task-qg-${item.id}" checked onchange="updateTaskPreview();saveDraft()">
              <div class="toggle-track"></div><div class="toggle-thumb"></div>
            </label>
          </div>`).join('')}
        </div>
        <div class="form-row">
          <label>Additional task-specific checks (one per line)</label>
          <textarea id="task-qg-custom" rows="2"
            placeholder="e.g. AppSettingsFragment does not call loadContactOptions() after this change — verify by grep"
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="form-section">
        <h3>Out of Scope</h3>
        <div class="form-row">
          <label>One item per line — explicitly state what NOT to do</label>
          <textarea id="task-oos" rows="3"
            placeholder="Do not add Adjust tracking — Firebase only&#10;Do not modify existing trackBasketTransfer() method"
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="form-section">
        <h3>Affected Areas</h3>
        <div class="form-row">
          <label>Module names, feature names, key files — helps agent load the right context files</label>
          <input type="text" id="task-areas"
            placeholder="e.g. analytics, store selection, SelectStoreFragment, StoreViewModel"
            oninput="updateTaskPreview();saveDraft()">
        </div>
      </div>

      <div class="form-section">
        <h3>Testing</h3>
        <div style="display:flex;gap:20px;flex-wrap:wrap">
          <div class="form-row" style="margin-bottom:0">
            <label>Required</label>
            <div class="radio-group">
              ${pill('Yes','Y','task-test-req','radio')}
              ${pill('No','N','task-test-req','radio')}
            </div>
          </div>
          <div class="form-row" style="margin-bottom:0">
            <label>Level</label>
            <div class="radio-group">
              ${pill('Unit','Unit','task-level','radio')}
              ${pill('Integration','Integration','task-level','radio')}
              ${pill('Both','Both','task-level','radio')}
            </div>
          </div>
        </div>
        <div class="form-row" style="margin-top:12px">
          <label>Scenarios (one per line)</label>
          <textarea id="task-scenarios" rows="3"
            placeholder="event fires with correct store_id when store is tapped&#10;event does not fire when store selection is cancelled"
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="form-section">
        <h3>Designs / References</h3>
        <div class="form-row">
          <label>One link or file path per line</label>
          <textarea id="task-refs" rows="2"
            placeholder="https://figma.com/file/...&#10;docs/api-contract.md"
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="form-section">
        <h3>Notes</h3>
        <div class="form-row">
          <label>Backend changes, known gotchas, ticket dependencies — leave blank if none</label>
          <textarea id="task-notes" rows="3"
            placeholder="The endpoint is not yet deployed to production — test against staging only."
            oninput="updateTaskPreview();saveDraft()"></textarea>
        </div>
      </div>

      <div class="btn-actions">
        <button class="btn btn-success" onclick="saveTask()">💾 Save Task</button>
        <button class="btn btn-secondary" onclick="resetTaskForm()">↺ New Task</button>
      </div>

      <div style="margin-top:12px;padding-top:12px;border-top:1px solid var(--border)">
        <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px">
          <div>
            <button class="btn-run-claude" id="btnRunClaude" onclick="runWithClaude()" disabled>
              ▶ Run with Claude
            </button>
          </div>
          <div style="font-size:11px;color:var(--text-muted);line-height:1.5" id="companionHint">
            Start the companion first:
            <code style="font-size:10px;background:var(--surface2);padding:2px 6px;border-radius:3px;border:1px solid var(--border)">node agent-sdd/companion.js</code>
          </div>
        </div>

        <!-- Terminal output panel -->
        <div class="claude-terminal" id="claudeTerminal">
          <div class="claude-terminal-header">
            <div class="claude-terminal-title">
              <div class="terminal-spinner" id="terminalSpinner"></div>
              <span id="terminalTitle">Claude Output</span>
            </div>
            <button class="btn btn-secondary btn-sm" onclick="document.getElementById('claudeTerminal').classList.remove('visible')">✕</button>
          </div>
          <div class="claude-terminal-body" id="claudeTerminalBody"></div>
        </div>
      </div>

    </div>
  </div>`;
}

// ══════════════════════════════════════════════════════
//  PLATFORM SELECTION
//  Dynamically loads platform-android.js or platform-ios.js
//  after the user picks a platform from the overlay.
// ══════════════════════════════════════════════════════
function choosePlatform(name) {
  const overlay = document.getElementById('platformOverlay');

  if (overlay) {
    overlay.style.opacity = '0';
    overlay.style.pointerEvents = 'none';
  }

  const script = document.createElement('script');
  script.src = 'engine/platform-' + name + '.js';

  script.onload = () => {
    setTimeout(() => overlay?.remove(), 320);
    // Skip interstitial on browsers without File System Access API
    if (!hasFSA) { init(); return; }
    showFolderInterstitial(name);
  };

  script.onerror = () => {
    if (overlay) { overlay.style.opacity = '1'; overlay.style.pointerEvents = ''; }
    showToast('Could not load platform: ' + name, 'error');
  };

  document.head.appendChild(script);
}

function showFolderInterstitial(platformName) {
  const label = platformName === 'android' ? 'Android' : 'iOS';

  const el = document.createElement('div');
  el.id = 'folderInterstitial';
  el.style.cssText = 'position:fixed;inset:0;z-index:200;display:flex;align-items:center;justify-content:center;background:var(--bg)';
  el.innerHTML = `
    <div style="text-align:center;max-width:460px;padding:48px 28px">
      <div style="font-size:48px;margin-bottom:20px">📂</div>
      <h2 style="margin:0 0 10px;font-size:22px;font-weight:700">Select your ${label} project folder</h2>
      <p style="color:var(--text-muted);font-size:14px;line-height:1.7;margin:0 0 32px">
        Point the wizard at your project root so it can auto-detect your stack and save all generated files directly into <code>agent-artifacts/</code> inside it.
      </p>
      <button id="folderInterstitialBtn" class="btn btn-primary" style="width:100%;justify-content:center;font-size:15px;padding:14px 24px;margin-bottom:16px">
        📂 Select Project Folder
      </button>
      <div>
        <button id="folderInterstitialSkip" style="background:none;border:none;color:var(--text-muted);font-size:13px;cursor:pointer;text-decoration:underline;padding:4px 0">
          Skip — I'll select it later
        </button>
      </div>
    </div>`;
  document.body.appendChild(el);

  const dismiss = (handle) => {
    el.style.transition = 'opacity 0.2s';
    el.style.opacity = '0';
    setTimeout(() => {
      el.remove();
      init();
      // Fire post-init folder setup now that DOM is fully built
      if (handle) {
        const badge = document.getElementById('sddBadge');
        if (badge) { badge.textContent = '📂 ' + handle.name; badge.className = 'folder-badge granted'; }
        const pathEl = document.getElementById('cfg-codebase-path');
        if (pathEl && !pathEl.value) pathEl.value = '..';
        tryReadFile(handle, 'agent-artifacts', 'project.config.md').then(existing => {
          if (existing) loadExistingConfig(existing);
        });
        showToast('Project folder set: ' + handle.name + ' — analysing…', 'success');
        PLATFORM.onFolderGranted?.();
        // Light up sidebar ✅ for any steps whose output files already exist
        detectExistingOutputFiles(handle);
      }
    }, 200);
  };

  document.getElementById('folderInterstitialBtn').onclick = async () => {
    try {
      const handle = await window.showDirectoryPicker();
      state.dirHandle = handle;
      dismiss(handle);
    } catch (e) {
      if (e.name !== 'AbortError') showToast('Could not access folder — try again.', 'error');
    }
  };

  document.getElementById('folderInterstitialSkip').onclick = () => dismiss(null);
}

// ══════════════════════════════════════════════════════
//  KEYBOARD NAVIGATION
// ══════════════════════════════════════════════════════
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') {
    document.getElementById('previewPanel').classList.add('collapsed');
  }
});

// DOMContentLoaded — do NOT call init() here.
// The platform overlay is already visible; init() is called by choosePlatform()
// once the user selects a platform and its script has loaded.
window.addEventListener('DOMContentLoaded', () => {
  applyBrowserCompat();
  startCompanionPolling();
});
