#!/usr/bin/env bash
# PreToolUse hook — blocks writes to generated/tool files that agents must never touch.
# Covers both direct file tool calls (Write/Edit/MultiEdit) and Bash commands
# that write to protected paths (sed -i, echo >>, mv, cp, tee, etc.).

INPUT=$(cat)

# ── Extract file path from direct file-tool calls (Write / Edit / MultiEdit) ─
FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', '') or
          data.get('tool_input', {}).get('path', ''))
except Exception:
    print('')
" 2>/dev/null)

# ── Extract Bash command (if the tool is Bash) ────────────────────────────────
BASH_CMD=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    if data.get('tool_name', '').lower() == 'bash':
        print(data.get('tool_input', {}).get('command', ''))
    else:
        print('')
except Exception:
    print('')
" 2>/dev/null)

if [ -z "$FILE_PATH" ] && [ -z "$BASH_CMD" ]; then
  exit 0
fi

# Normalize to a path relative to the project root so matching works whether the
# agent used a relative path (agent-artifacts/...) or an absolute one
# (/Users/me/project/agent-artifacts/...). The hook runs with CWD = project root.
CLEAN="$FILE_PATH"
ROOT="${PWD%/}"
CLEAN="${CLEAN#"$ROOT"/}"
CLEAN="${CLEAN#./}"

deny() {
  local reason="$1"
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"'"$reason"'"}}'
  exit 0
}

# ── Tool / artifacts protection ───────────────────────────────────────────────
# Patterns match both the project-relative form and an absolute/nested form
# (*/agent-artifacts/...) so an absolute path is still caught.
[[ "$CLEAN" == agent-sdd/* || "$CLEAN" == */agent-sdd/* ]] \
  && deny "agent-sdd/ is the read-only SDD tool — never modify it directly."
[[ "$CLEAN" == agent-artifacts/CLAUDE.md || "$CLEAN" == */agent-artifacts/CLAUDE.md ]] \
  && deny "agent-artifacts/CLAUDE.md is a read-only snapshot — re-run the setup wizard to update it."
[[ "$CLEAN" == agent-artifacts/spec-kit/* || "$CLEAN" == */agent-artifacts/spec-kit/* ]] \
  && deny "spec-kit/ files are read-only — re-run the wizard to regenerate AI artifacts, or edit human-authored specs directly."

# ── iOS generated / project files ────────────────────────────────────────────
[[ "$CLEAN" == *.xcodeproj/* || "$CLEAN" == *.xcodeproj ]] && deny "Xcode project files are managed by Xcode — do not modify programmatically."
[[ "$CLEAN" == *.xcworkspace/* || "$CLEAN" == *.xcworkspace ]] && deny "Xcode workspace files are managed by Xcode — do not modify programmatically."

# ── Android generated files ───────────────────────────────────────────────────
[[ "$CLEAN" == */BuildConfig.java ]]       && deny "BuildConfig.java is auto-generated by Gradle — edit build.gradle instead."
[[ "$CLEAN" == */R.java ]]                 && deny "R.java is auto-generated by AAPT — edit resource XML files instead."
[[ "$CLEAN" == *.generated.kt ]]           && deny "*.generated.kt files are auto-generated — do not modify directly."
[[ "$CLEAN" == **/gradlew || "$CLEAN" == gradlew ]] && deny "gradlew is auto-generated — do not modify."
[[ "$CLEAN" == **/gradlew.bat || "$CLEAN" == gradlew.bat ]] && deny "gradlew.bat is auto-generated — do not modify."

# ── Build output directories ──────────────────────────────────────────────────
[[ "$CLEAN" == */build/* || "$CLEAN" == build/* ]] && deny "build/ is a generated output directory — do not write files here."
[[ "$CLEAN" == DerivedData/* || "$CLEAN" == */DerivedData/* ]] && deny "DerivedData/ is Xcode's build cache — do not write files here."

# ── Bash write detection ──────────────────────────────────────────────────────
# Guard against Bash commands that write to protected paths.
# Checks for: sed -i, echo/printf >, >>, mv, cp, tee, install targeting a protected path.
if [ -n "$BASH_CMD" ]; then
  PROTECTED_PATTERN='agent-artifacts/CLAUDE\.md|agent-artifacts/spec-kit/|agent-sdd/'
  WRITE_OPS_PATTERN='sed[[:space:]]+-i|>|>>|[[:space:]]mv[[:space:]]|[[:space:]]cp[[:space:]]|[[:space:]]tee[[:space:]]|[[:space:]]install[[:space:]]'

  if echo "$BASH_CMD" | grep -qE "$PROTECTED_PATTERN" && \
     echo "$BASH_CMD" | grep -qE "$WRITE_OPS_PATTERN"; then
    deny "Bash write to a protected path detected — agent-artifacts/spec-kit/, agent-artifacts/CLAUDE.md, and agent-sdd/ are read-only. Use the wizard to regenerate AI artifacts."
  fi
fi

exit 0
