#!/usr/bin/env bash
# PreToolUse hook — blocks writes to generated/tool files that agents must never touch.
# Claude Code passes tool input via stdin as JSON.
# Exit 0 + JSON deny response = block the tool call.
# Exit 0 + no output = allow through.

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', '') or
          data.get('tool_input', {}).get('path', ''))
except Exception:
    print('')
" 2>/dev/null)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Normalize: strip leading ./
CLEAN="${FILE_PATH#./}"

deny() {
  local reason="$1"
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"'"$reason"'"}}'
  exit 0
}

# ── Tool / skeleton protection ────────────────────────────────────────────────
[[ "$CLEAN" == agent-sdd/* ]]              && deny "agent-sdd/ is the read-only SDD tool — never modify it directly."
[[ "$CLEAN" == agent-sdd-output/spec-kit/* ]] && deny "spec-kit/ files are human-authored specs — re-run the wizard to regenerate AI artifacts, or edit the file manually."

# ── iOS generated / project files ────────────────────────────────────────────
[[ "$CLEAN" == *.xcodeproj/* || "$CLEAN" == *.xcodeproj ]] && deny "Xcode project files are managed by Xcode — do not modify programmatically."
[[ "$CLEAN" == *.xcworkspace/* || "$CLEAN" == *.xcworkspace ]] && deny "Xcode workspace files are managed by Xcode — do not modify programmatically."

# ── Android generated files ───────────────────────────────────────────────────
[[ "$CLEAN" == */BuildConfig.java ]]       && deny "BuildConfig.java is auto-generated by Gradle — edit build.gradle instead."
[[ "$CLEAN" == */R.java ]]                 && deny "R.java is auto-generated by AAPT — edit resource XML files instead."
[[ "$CLEAN" == *.generated.kt ]]           && deny "*.generated.kt files are auto-generated — do not modify directly."
[[ "$CLEAN" == **/gradlew || "$CLEAN" == gradlew ]] && deny "gradlew is auto-generated by Gradle wrapper — do not modify."
[[ "$CLEAN" == **/gradlew.bat || "$CLEAN" == gradlew.bat ]] && deny "gradlew.bat is auto-generated by Gradle wrapper — do not modify."

# ── Build output directories ──────────────────────────────────────────────────
[[ "$CLEAN" == */build/* || "$CLEAN" == build/* ]] && deny "build/ is a generated output directory — do not write files here."
[[ "$CLEAN" == DerivedData/* || "$CLEAN" == */DerivedData/* ]] && deny "DerivedData/ is Xcode's build cache — do not write files here."

exit 0
